[package]
name = "deaftone_rust"
version = "0.1.0"
edition = "2021"


[workspace]
members = [".", "entity", "migration"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" } 
axum = "0.5.13"
tokio = { version = "1.20.0", features = ["full"] }
tower-http = { version = "0.3.0", features = ["trace", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = "0.4.19"
anyhow = "1.0.58"
walkdir = "2.3.2"
metaflac = "0.2.5"
tokio-util = "0.7.3"
tower = "0.4.13"
serde = { version = "1.0"}
serde_json = { version = "1.0.71" }
[dependencies.sea-orm]
version = "^0.9.1" # sea-orm version
features = [
  "debug-print",
  "runtime-tokio-native-tls",
  "sqlx-sqlite",
]

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
]
