//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub use super::album::Entity as Album;
pub use super::artists::Entity as Artist;
pub use super::directories::Entity as Directorie;
pub use super::songs::Entity as Songs;
