//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "songs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub path: String,
    pub title: String,
    pub disk: Option<i32>,
    pub artist: String,
    #[sea_orm(column_name = "albumName")]
    pub album_name: String,
    pub codec: Option<String>,
    pub duration: u32,
    #[sea_orm(column_name = "sampleRate")]
    pub sample_rate: Option<String>,
    #[sea_orm(column_name = "bitsPerSample")]
    pub bits_per_sample: Option<i32>,
    pub track: Option<i32>,
    pub year: Option<i32>,
    pub label: Option<String>,
    #[sea_orm(column_name = "musicBrainzRecordingId")]
    pub music_brainz_recording_id: Option<String>,
    #[sea_orm(column_name = "musicBrainzArtistId")]
    pub music_brainz_artist_id: Option<String>,
    #[sea_orm(column_name = "musicBrainzTrackId")]
    pub music_brainz_track_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: String,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: String,
    #[sea_orm(column_name = "albumId")]
    pub album_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::album::Entity",
        from = "Column::AlbumId",
        to = "super::album::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Album,
}

impl Related<super::album::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Album.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
